### PR TITLE
fix: Replace Hosted Mender references with `global.url` in workflows

### PR DESCRIPTION
**Pull request by alfrunes**
Depends on mendersoftware/workflows-enterprise#359

### CODE REVIEW

**Comment by alfrunes** [comment]
@merlin-northern this doesn't make the email templates fully customizable, but at least it updates the reference to the configured server url. Should we expose all workflows email templates as customizable variables?

**Comment by tranchitella** [comment]
@alfrunes honestly, I don't think so.

**Review by tranchitella — APPROVED** [review]

**Comment by merlin-northern** [comment]
> @merlin-northern this doesn't make the email templates fully customizable, but at least it updates the reference to the configured server url. Should we expose all workflows email templates as customizable variables?

we had no request for that. assuming you have your own template there is a similar amount of work required to provide it in the env or to replace it in the workflows pod, right? so I believe we are fine here. I have also forwarded you the original request, just as a refresher, we discussed that a long time ago.

**Review by merlin-northern — COMMENTED** [review]
the change looks good, but see my comment.

**Review by merlin-northern — APPROVED** [review]

**Comment by alfrunes** [comment]
> my question is, what does this change? the original problem: onprem installs send 2fa and password reset emails with hard coded server url, this is still the case:
> 
> ```shell
> # cat worker/password_reset_email.txt
> Dear Mender User,
> 
> You recently requested to reset your password for your Mender account.
> Click the link below or copy and paste the link into your browser
> to reset your password:
> 
> https://hosted.mender.io/ui/#/password/${workflow.input.secret_hash}
> ```
> 
> we need some followups in the workflows, right?

This is exactly what the accompanying PR (mendersoftware/workflows-enterprise#359) is doing, it replaces all hard-coded references to Hosted Mender with a template variable exposed as an environment variable.

**Pull request merged**
