### PR TITLE
Option to use existing secrets for certificates

### PR DESCRIPTION
**Pull request by bdomars**
The current way of creating the secrets for certs via the Helm charts does not  work well with external secret management tools like Vault and Vault webhook. 

This PR adds an existingSecret parameter to all `certs` to not have the Helm chart render the secrets and instead letting the external tools manage them.

### CODE REVIEW

**Comment by oldgiova** [comment]
Hello @bdomars thanks for your valuable contribution! Could you please signoff your commits? [More details](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md#sign-your-work).

Thanks!

**Comment by oldgiova** [comment]
Not to self: if approved I have to update the README.md with `api_gateway.certs.` documentation

**Comment by bdomars** [comment]
Oh, I missed the contributions guidelines in your main repo, sorry :)

Reworded the commit messages with sign-offs now.

**Comment by bdomars** [comment]
Of course, I'll change it.

**Review by oldgiova — APPROVED** [review]
LGTM :+1:

**Pull request merged**
